### PR TITLE
Try: Fixing the gulptask.

### PR DESCRIPTION
**Pull request by praveenscience**
This is a try to fix it right way. If this doesn't work, let's try another.

### CODE REVIEW

**Comment by praveenscience** [comment]
Wait, what you might want is this too: https://stackoverflow.com/questions/49650419/gulp-task-to-replace-all-root-relative-urls-with-document-relative-urls

Kindly check this as well.

**Review by IndranilMajee — APPROVED** [review]

**Comment by praveenscience** [comment]
@im8kritika or @IndranilMajee Let me know if this works, if it doesn't, I have another idea too. Can you share the deployment log if this doesn't work?

**Comment by im8kritika** [comment]
@praveenscience  Still not working, my css and js are stored inside dist folder, if i individually select index.html, css and js from dist , it works fine as a static website

**Comment by praveenscience** [comment]
@im8kritika Can you share the deployment log? You haven't added the `gulp` as dependency, but it should work because of the others. Now without knowing the exact error right now, it's difficult. Hence share the log.

**Comment by im8kritika** [comment]
@praveenscience https://github.com/im8kritika/wordle-/invitations     

I am changing to owner , kindly do whats nedded, i cant get the option to send log

**Comment by praveenscience** [comment]
@im8kritika I don't think I still get the option to see deployments or actions:
image

**Comment by praveenscience** [comment]
All I see is just this:
image
Is it possible for us to connect through Zoom for a quick screenshare?

**Comment by im8kritika** [comment]
@praveenscience i am not getting the option to change u from collaborator to owner
Screenshot 2023-12-10 205356

https://us05web.zoom.us/j/86768488862?pwd=NtyybGddaYsLXNwpvwn2bb80BqrNZz.1
zoom link

**Comment by praveenscience** [comment]
Missed it, I couldn't connect. Can you try joining my Zoom Rooms? It's a Pro one. Hope it works:
https://us06web.zoom.us/j/87265555287?pwd=1svVpetzLrw8dotk6jEzZmC0B3YlYU.1
Please come in. 💪🏻

**Comment by praveenscience** [comment]
> @praveenscience i am not getting the option to change u from collaborator to owner Screenshot 2023-12-10 205356
> 
> https://us05web.zoom.us/j/86768488862?pwd=NtyybGddaYsLXNwpvwn2bb80BqrNZz.1 zoom link

No don't change. Let's do Zoom:
https://us06web.zoom.us/j/87265555287?pwd=1svVpetzLrw8dotk6jEzZmC0B3YlYU.1

**Comment by im8kritika** [comment]
@praveenscience see i changed the file, but still nothing helped. lol i seperate the css and js , it started running
https://wordle-dev.pages.dev/

**Comment by praveenscience** [comment]
> @praveenscience see i changed the file, but still nothing helped. lol i seperate the css and js , it started running https://wordle-dev.pages.dev/

Amazing! 💪

**Pull request merged**
